Fix Terraform AWS provider at version 2.69
The current Terraform config is incompatible with higher AWS provider
versions.

With version 2.70, we get errors like:

```
Error: Unsupported block type

  on tdr-terraform-modules/ecr/main.tf line 5, in resource "aws_ecr_repository" "ecr_repository":
   5:   image_scanning_configuration {

Blocks of type "image_scanning_configuration" are not expected here.
```

With version 3, we get errors like:

```
Error: Invalid index

  on tdr-terraform-modules/certificatemanager/main.tf line 22, in resource "aws_route53_record" "cert_validation":
  22:   name    = aws_acm_certificate.cert.domain_validation_options.0.resource_record_name

This value does not have any indices.
```

Upgrading the provider is part of Jira card TDR-500.