Roll back the amazon-ecs plugin
Roll back from version 1.32 to 1.31, because version 1.32 introduces a bug
which causes builds like the frontend build to fail with the error:

```
java.lang.IllegalArgumentException: You must specify an image
    at com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate.<init>(ECSTaskTemplate.java:329)
```

This seem to be the issue: https://github.com/jenkinsci/amazon-ecs-plugin/issues/139#issuecomment-616396170